server:
  port: "8080"
  host: "localhost"

database:
  dsn: "ryon:123456@tcp(127.0.0.1:3306)/movie_reservation_system?charset=utf8mb4&parseTime=True&loc=Local"
  maxOpenConnections: 10
  maxIdleConnections: 5

redis:
  addr: 127.0.0.1:6379
  password: "" # 默认不需要
  db: 0        # 数据库编号

jwt:
  secretKey: "your-256-bit-secret"
  accessTokenDuration: 15m
  refreshTokenDuration: 72h

log:
  level: debug
  outputPaths: ["stdout", "./var/log/app.log"]
  errorOutputPaths: ["stderr", "./var/log/error.log"]
  encoding: json
  development_mode: true
